//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Saving error!.
        /// </summary>
        public static string ___Save_error_ {
            get {
                return ResourceManager.GetString("___Save_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Successfully saved into files.
        /// </summary>
        public static string ___Successfully_saved_into_files {
            get {
                return ResourceManager.GetString("___Successfully_saved_into_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: loading daily expenses....
        /// </summary>
        public static string @__0__loading_daily_expenses__FORMAT__ {
            get {
                return ResourceManager.GetString("__0__loading_daily_expenses__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists with the specified name. .
        /// </summary>
        public static string _0__already_exists_with_the_specified_name__ {
            get {
                return ResourceManager.GetString("_0__already_exists_with_the_specified_name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not implemented for context type: {1}, using DbType configuration: {2}.
        /// </summary>
        public static string _0__is_not_implemented_for_context_type___1___using_DbType_configuration___2_ {
            get {
                return ResourceManager.GetString("_0__is_not_implemented_for_context_type___1___using_DbType_configuration___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  daily .
        /// </summary>
        public static string _daily_ {
            get {
                return ResourceManager.GetString("_daily_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  daily expenses.
        /// </summary>
        public static string _daily_expenses {
            get {
                return ResourceManager.GetString("_daily_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  daily expenses successfully saved. .
        /// </summary>
        public static string _daily_expenses_successfully_saved_ {
            get {
                return ResourceManager.GetString("_daily_expenses_successfully_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- end -- .
        /// </summary>
        public static string _end_ {
            get {
                return ResourceManager.GetString("_end_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  expense statistics successfully saved. .
        /// </summary>
        public static string _expense_statistics_successfully_saved_ {
            get {
                return ResourceManager.GetString("_expense_statistics_successfully_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ┌-(from this, database).
        /// </summary>
        public static string _from_this__database_ {
            get {
                return ResourceManager.GetString("_from_this__database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  monthly .
        /// </summary>
        public static string _monthly_ {
            get {
                return ResourceManager.GetString("_monthly_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  monthly incomes.
        /// </summary>
        public static string _monthly_incomes {
            get {
                return ResourceManager.GetString("_monthly_incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pc).
        /// </summary>
        public static string _pc_ {
            get {
                return ResourceManager.GetString("_pc_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Again.
        /// </summary>
        public static string Again {
            get {
                return ResourceManager.GetString("Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All created successfully. .
        /// </summary>
        public static string All_created_successfully {
            get {
                return ResourceManager.GetString("All_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All created successfully. .
        /// </summary>
        public static string All_created_successfully_ {
            get {
                return ResourceManager.GetString("All_created_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount: .
        /// </summary>
        public static string Amount_ {
            get {
                return ResourceManager.GetString("Amount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating summaries.
        /// </summary>
        public static string Calculating_summaries {
            get {
                return ResourceManager.GetString("Calculating_summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        public static string Category_ {
            get {
                return ResourceManager.GetString("Category_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exists with the specified name. .
        /// </summary>
        public static string Category_already_exists_with_the_specified_name {
            get {
                return ResourceManager.GetString("Category_already_exists_with_the_specified_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string Category_lowercase {
            get {
                return ResourceManager.GetString("Category_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryManagerAdoNetFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string CategoryManagerAdoNetFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("CategoryManagerAdoNetFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryManagerCommonBase.RefreshCache is not implemented for ReadMode: .
        /// </summary>
        public static string CategoryManagerCommonBase_RefreshCache_is_not_implemented_for_ReadMode__ {
            get {
                return ResourceManager.GetString("CategoryManagerCommonBase_RefreshCache_is_not_implemented_for_ReadMode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryManagerEfFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string CategoryManagerEfFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("CategoryManagerEfFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments are not implemented yet.
        /// </summary>
        public static string Command_line_arguments_are_not_implemented_yet {
            get {
                return ResourceManager.GetString("Command_line_arguments_are_not_implemented_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment: .
        /// </summary>
        public static string Comment_ {
            get {
                return ResourceManager.GetString("Comment_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error: can&apos;t use ReadMode.FromDb and SaveMode.OnlyToFile together. .
        /// </summary>
        public static string Configuration_error__can_t_use_ReadMode_FromDb_and_SaveMode_OnlyToFile_together__ {
            get {
                return ResourceManager.GetString("Configuration_error__can_t_use_ReadMode_FromDb_and_SaveMode_OnlyToFile_together__" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy menuitem is not implemented yet.
        /// </summary>
        public static string Copy_menuitem_is_not_implemented_yet {
            get {
                return ResourceManager.GetString("Copy_menuitem_is_not_implemented_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying summary file into the summary directory - Error!.
        /// </summary>
        public static string Copying_summary_file_into_the_summary_directory___Error_ {
            get {
                return ResourceManager.GetString("Copying_summary_file_into_the_summary_directory___Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying summary file into the summary directory - OK.
        /// </summary>
        public static string Copying_summary_file_into_the_summary_directory___OK {
            get {
                return ResourceManager.GetString("Copying_summary_file_into_the_summary_directory___OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the {0} (ID: {1}) in the database.
        /// </summary>
        public static string Could_not_find_the__0___ID___1___in_the_database {
            get {
                return ResourceManager.GetString("Could_not_find_the__0___ID___1___in_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the {0} (Name: {1}) in the database.
        /// </summary>
        public static string Could_not_find_the__0___Name___1___in_the_database {
            get {
                return ResourceManager.GetString("Could_not_find_the__0___Name___1___in_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Category (DisplayName: {0}) in the database.
        /// </summary>
        public static string Could_not_find_the_Category__DisplayName_0__in_the_database__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_find_the_Category__DisplayName_0__in_the_database__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Category (ID: {0}) in the database.
        /// </summary>
        public static string Could_not_find_the_Category__ID_0__in_the_database__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_find_the_Category__ID_0__in_the_database__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Category (Name: {0}) in the database.
        /// </summary>
        public static string Could_not_find_the_Category__Name_0__in_the_database__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_find_the_Category__Name_0__in_the_database__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Exin&apos;s work directory here: {0}.
        /// </summary>
        public static string Could_not_find_the_Exin_s_work_directory_here__0__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_find_the_Exin_s_work_directory_here__0__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the monthly directory: .
        /// </summary>
        public static string Could_not_find_the_monthly_directory_ {
            get {
                return ResourceManager.GetString("Could_not_find_the_monthly_directory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the monthly directory:
        ///.
        /// </summary>
        public static string Could_not_find_the_root_directory {
            get {
                return ResourceManager.GetString("Could_not_find_the_root_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Solution&apos;s root directory. .
        /// </summary>
        public static string Could_not_find_the_Solution_s_root_directory_ {
            get {
                return ResourceManager.GetString("Could_not_find_the_Solution_s_root_directory_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the SQLite database file (here: {0}).
        /// </summary>
        public static string Could_not_find_the_SQLite_database_file__here__0__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_find_the_SQLite_database_file__here__0__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Unit (DisplayName: {0}) in the database.
        /// </summary>
        public static string Could_not_find_the_Unit__DisplayName_0__in_the_database__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_find_the_Unit__DisplayName_0__in_the_database__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert the Category record. .
        /// </summary>
        public static string Could_not_insert_the_Category_record {
            get {
                return ResourceManager.GetString("Could_not_insert_the_Category_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert the transaction item:.
        /// </summary>
        public static string Could_not_insert_the_transaction_item_ {
            get {
                return ResourceManager.GetString("Could_not_insert_the_transaction_item_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert the transaction items (.
        /// </summary>
        public static string Could_not_insert_the_transaction_items_ {
            get {
                return ResourceManager.GetString("Could_not_insert_the_transaction_items_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert the Unit record. .
        /// </summary>
        public static string Could_not_insert_the_Unit_record {
            get {
                return ResourceManager.GetString("Could_not_insert_the_Unit_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the database connection. .
        /// </summary>
        public static string Could_not_open_the_database_connection {
            get {
                return ResourceManager.GetString("Could_not_open_the_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the daily {0} at {1}.
        /// </summary>
        public static string Could_not_remove_the_daily_0_at_1__FORMAT__ {
            get {
                return ResourceManager.GetString("Could_not_remove_the_daily_0_at_1__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the transaction record (TransactionItem, ID: .
        /// </summary>
        public static string Could_not_remove_the_transaction_record__TransactionItem__ID_ {
            get {
                return ResourceManager.GetString("Could_not_remove_the_transaction_record__TransactionItem__ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save into database the daily expense statistics. .
        /// </summary>
        public static string Could_not_save_into_database_the_daily_expense_statistics {
            get {
                return ResourceManager.GetString("Could_not_save_into_database_the_daily_expense_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the daily expenses!
        ///.
        /// </summary>
        public static string Could_not_save_the_daily_expenses_ {
            get {
                return ResourceManager.GetString("Could_not_save_the_daily_expenses_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the monthly incomes!
        ///.
        /// </summary>
        public static string Could_not_save_the_monthly_incomes_ {
            get {
                return ResourceManager.GetString("Could_not_save_the_monthly_incomes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the transaction record (TransactionItem, ID: .
        /// </summary>
        public static string Could_not_update_the_transaction_record__TransactionItem__ID_ {
            get {
                return ResourceManager.GetString("Could_not_update_the_transaction_record__TransactionItem__ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - OK.
        /// </summary>
        public static string Created___0__FORMAT__ {
            get {
                return ResourceManager.GetString("Created___0__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DbParameter to DbType: {0} is not implemented. .
        /// </summary>
        public static string Creating_DbParameter_to_DbType___0__is_not_implemented_ {
            get {
                return ResourceManager.GetString("Creating_DbParameter_to_DbType___0__is_not_implemented_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating or emptying tables.
        /// </summary>
        public static string Creating_or_emptying_tables {
            get {
                return ResourceManager.GetString("Creating_or_emptying_tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the monthly files: .
        /// </summary>
        public static string Creating_the_monthly_files_ {
            get {
                return ResourceManager.GetString("Creating_the_monthly_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily expenses.
        /// </summary>
        public static string Daily_expenses {
            get {
                return ResourceManager.GetString("Daily_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily expenses.
        /// </summary>
        public static string daily_expenses__LowerCase {
            get {
                return ResourceManager.GetString("daily_expenses__LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily expenses saved successfully. .
        /// </summary>
        public static string Daily_expenses_saved_successfully__ {
            get {
                return ResourceManager.GetString("Daily_expenses_saved_successfully__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily files read successfully.
        /// </summary>
        public static string Daily_files_read_successfully {
            get {
                return ResourceManager.GetString("Daily_files_read_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily summary: .
        /// </summary>
        public static string Daily_sum {
            get {
                return ResourceManager.GetString("Daily_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.MM.dd.
        /// </summary>
        public static string DateFormat_full {
            get {
                return ResourceManager.GetString("DateFormat_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.dd.
        /// </summary>
        public static string DateFormat_month_day {
            get {
                return ResourceManager.GetString("DateFormat_month_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy .
        /// </summary>
        public static string DateFormat_year_ {
            get {
                return ResourceManager.GetString("DateFormat_year_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.MM.
        /// </summary>
        public static string DateFormat_year_month {
            get {
                return ResourceManager.GetString("DateFormat_year_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        public static string Directory_not_found {
            get {
                return ResourceManager.GetString("Directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty_ {
            get {
                return ResourceManager.GetString("Empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access mode: AdoNet.
        /// </summary>
        public static string Enum_DbAccessMode_AdoNet {
            get {
                return ResourceManager.GetString("Enum_DbAccessMode_AdoNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access mode: EntityFramework.
        /// </summary>
        public static string Enum_DbAccessMode_EntityFramework {
            get {
                return ResourceManager.GetString("Enum_DbAccessMode_EntityFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null value, only for internal use.
        /// </summary>
        public static string Enum_DbAccessMode_None {
            get {
                return ResourceManager.GetString("Enum_DbAccessMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type: MS SQL Server.
        /// </summary>
        public static string Enum_DbType_MsSql {
            get {
                return ResourceManager.GetString("Enum_DbType_MsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type: SQLite.
        /// </summary>
        public static string Enum_DbType_SQLite {
            get {
                return ResourceManager.GetString("Enum_DbType_SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read data: from database.
        /// </summary>
        public static string Enum_ReadMode_FromDb {
            get {
                return ResourceManager.GetString("Enum_ReadMode_FromDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read data: from file repository.
        /// </summary>
        public static string Enum_ReadMode_FromFile {
            get {
                return ResourceManager.GetString("Enum_ReadMode_FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data: to file system and database.
        /// </summary>
        public static string Enum_SaveMode_FileAndDb {
            get {
                return ResourceManager.GetString("Enum_SaveMode_FileAndDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data: only to file system.
        /// </summary>
        public static string Enum_SaveMode_OnlyToFile {
            get {
                return ResourceManager.GetString("Enum_SaveMode_OnlyToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumDescriptionConverter.ConvertBack is not supported. .
        /// </summary>
        public static string EnumDescriptionConverter_ConvertBack_is_not_supported__ {
            get {
                return ResourceManager.GetString("EnumDescriptionConverter_ConvertBack_is_not_supported__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error_ {
            get {
                return ResourceManager.GetString("Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! More than one exists from files starting with &apos;{0}&apos;:.
        /// </summary>
        public static string Error__More_than_one_exists_from_files_starting_with__0__FORMAT__ {
            get {
                return ResourceManager.GetString("Error__More_than_one_exists_from_files_starting_with__0__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while creating the SQLite database file. .
        /// </summary>
        public static string Error_occured_while_creating_the_SQLite_database_file {
            get {
                return ResourceManager.GetString("Error_occured_while_creating_the_SQLite_database_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExinAdoNetContextFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string ExinAdoNetContextFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("ExinAdoNetContextFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExinConnectionString&apos;s ctor is not implemented for {0}.
        /// </summary>
        public static string ExinConnectionString_s_ctor_is_not_implemented_for__0_ {
            get {
                return ResourceManager.GetString("ExinConnectionString_s_ctor_is_not_implemented_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExinConnectionStringManagerBase&apos;s ctor is not implemented for {0}.
        /// </summary>
        public static string ExinConnectionStringManagerBase_s_ctor_is_not_implemented_for__0_ {
            get {
                return ResourceManager.GetString("ExinConnectionStringManagerBase_s_ctor_is_not_implemented_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExinEfContextFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string ExinEfContextFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("ExinEfContextFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expenses.
        /// </summary>
        public static string expenses {
            get {
                return ResourceManager.GetString("expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnumValues needs an enum input. .
        /// </summary>
        public static string GetEnumValues_needs_an_enum_input__ {
            get {
                return ResourceManager.GetString("GetEnumValues_needs_an_enum_input__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity insert using MS SQL with EntityFramework is not implemented. Use the (simple) Ado.Net version instead. .
        /// </summary>
        public static string Identity_insert_using_MS_SQL_with_EntityFramework_is_not_implemented__Use_the__simple__Ado_Net_version_instead__ {
            get {
                return ResourceManager.GetString("Identity_insert_using_MS_SQL_with_EntityFramework_is_not_implemented__Use_the__si" +
                        "mple__Ado_Net_version_instead__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity insert using SQLite with EntityFramework is not implemented. Use the (simple) Ado.Net version instead. .
        /// </summary>
        public static string Identity_insert_using_SQLite_with_EntityFramework_is_not_implemented__Use_the__simple__Ado_Net_version_instead__ {
            get {
                return ResourceManager.GetString("Identity_insert_using_SQLite_with_EntityFramework_is_not_implemented__Use_the__si" +
                        "mple__Ado_Net_version_instead__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportData.ClearAllTables is not implemented to this DbType: {0}.
        /// </summary>
        public static string ImportData_ClearAllTables_is_not_implemented_to_this_DbType___0_ {
            get {
                return ResourceManager.GetString("ImportData_ClearAllTables_is_not_implemented_to_this_DbType___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing categories.
        /// </summary>
        public static string Importing_categories {
            get {
                return ResourceManager.GetString("Importing_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing data from File Repository into ({0}) DataBase....
        /// </summary>
        public static string Importing_data_from_File_Repository_into___0___DataBase {
            get {
                return ResourceManager.GetString("Importing_data_from_File_Repository_into___0___DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing expenses and incomes.
        /// </summary>
        public static string Importing_expenses_and_incomes {
            get {
                return ResourceManager.GetString("Importing_expenses_and_incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing units.
        /// </summary>
        public static string Importing_units {
            get {
                return ResourceManager.GetString("Importing_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income statistics successfully saved. .
        /// </summary>
        public static string Income_statistics_successfully_saved_ {
            get {
                return ResourceManager.GetString("Income_statistics_successfully_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomes.
        /// </summary>
        public static string incomes {
            get {
                return ResourceManager.GetString("incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomes loading....
        /// </summary>
        public static string incomes_loading__ {
            get {
                return ResourceManager.GetString("incomes_loading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant .
        /// </summary>
        public static string Instant_ {
            get {
                return ResourceManager.GetString("Instant_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last written at: .
        /// </summary>
        public static string last_written_at__ {
            get {
                return ResourceManager.GetString("last_written_at__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading expenses....
        /// </summary>
        public static string loading_expenses__ {
            get {
                return ResourceManager.GetString("loading_expenses__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagerFactory is not implemented for: .
        /// </summary>
        public static string ManagerFactory_is_not_implemented_for__ {
            get {
                return ResourceManager.GetString("ManagerFactory_is_not_implemented_for__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There is no search functionality implemented in the Exin application at present.
        ///However, you can search among your expneses/incomes in the file system (eg using Total Commander: Alt+F7); 
        ///or if you are familiar with SQL queries, you can also use the SQLite database file for this..
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///-------------------
        ///Keyboard shortcuts:
        ///-------------------
        ///
        ///Alt + Right/Left: Step 1 day forth/back
        ///Alt + Up/Down: Step 1 month forth/back
        ///Alt + Shift + Up/Down: Step 1 year forth/back
        ///Alt + End: Jump to today
        ///Ctrl + S: Save
        ///(Shift) + Tab: Jump (backwards) among control elements
        ///Ctrl + (Shift) + Tab: Jump (backwards) among tabs
        ///
        ///--------------------------
        ///Accessable plus functions:
        ///--------------------------
        ///
        ///In lists:
        ///- The columns can be resorted
        ///- The columns can be resized
        ///- The  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Menu_Shortcuts {
            get {
                return ResourceManager.GetString("Menu_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly expenses.
        /// </summary>
        public static string Monthly_expenses {
            get {
                return ResourceManager.GetString("Monthly_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly incomes.
        /// </summary>
        public static string Monthly_incomes {
            get {
                return ResourceManager.GetString("Monthly_incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly incomes.
        /// </summary>
        public static string monthly_incomes__LowerCase {
            get {
                return ResourceManager.GetString("monthly_incomes__LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly incomes read successfully. .
        /// </summary>
        public static string Monthly_incomes_read_successfully {
            get {
                return ResourceManager.GetString("Monthly_incomes_read_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly incomes saved successfully. .
        /// </summary>
        public static string Monthly_incomes_saved_successfully__ {
            get {
                return ResourceManager.GetString("Monthly_incomes_saved_successfully__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly incomes successfully saved. .
        /// </summary>
        public static string Monthly_incomes_successfully_saved_ {
            get {
                return ResourceManager.GetString("Monthly_incomes_successfully_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly summary: .
        /// </summary>
        public static string Monthly_sum {
            get {
                return ResourceManager.GetString("Monthly_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly summary: .
        /// </summary>
        public static string Monthly_summary_ {
            get {
                return ResourceManager.GetString("Monthly_summary_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New daily expense.
        /// </summary>
        public static string New_daily_expense {
            get {
                return ResourceManager.GetString("New_daily_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New monthly income.
        /// </summary>
        public static string New_monthly_income {
            get {
                return ResourceManager.GetString("New_monthly_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation finished successfully! .
        /// </summary>
        public static string Operation_finished_successfully__ {
            get {
                return ResourceManager.GetString("Operation_finished_successfully__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options menuitem is not implemented yet.
        /// </summary>
        public static string Options_menuitem_is_not_implemented_yet {
            get {
                return ResourceManager.GetString("Options_menuitem_is_not_implemented_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait until it&apos;s done!.
        /// </summary>
        public static string Please__wait_until_it_s_done {
            get {
                return ResourceManager.GetString("Please__wait_until_it_s_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string Press_any_key_to_continue_ {
            get {
                return ResourceManager.GetString("Press_any_key_to_continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity: .
        /// </summary>
        public static string Quantity_ {
            get {
                return ResourceManager.GetString("Quantity_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} have to be at least {1}.
        /// </summary>
        public static string RangeMinErrorMessageFormat {
            get {
                return ResourceManager.GetString("RangeMinErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} have to be between {2} and {1}.
        /// </summary>
        public static string RangeMinMaxErrorMessageFormat {
            get {
                return ResourceManager.GetString("RangeMinMaxErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read successfully..
        /// </summary>
        public static string Read_successfully {
            get {
                return ResourceManager.GetString("Read_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading error!.
        /// </summary>
        public static string Reading_error_ {
            get {
                return ResourceManager.GetString("Reading_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading statistics from File Repository is not implemented. You see this message because the data read mode (ReadMode) is set to value &quot;FromFile&quot;. Set it to &quot;FromDb&quot; if you want to see statistics; otherwise you can only see them in the file system at:
        ///.
        /// </summary>
        public static string Reading_statistics_from_File_Repository_is_not_implemented___ETC_MSG {
            get {
                return ResourceManager.GetString("Reading_statistics_from_File_Repository_is_not_implemented___ETC_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: It can&apos;t be empty. It have to contain at least 1 character!.
        /// </summary>
        public static string RegEx_notEmptyOrWhiteSpace_errMsg {
            get {
                return ResourceManager.GetString("RegEx_notEmptyOrWhiteSpace_errMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: This is a numeric field, can only contain numbers!.
        /// </summary>
        public static string RegEx_onlyNumbers_errMsg {
            get {
                return ResourceManager.GetString("RegEx_onlyNumbers_errMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Only english letters and numbers are permitted (it also have to start with a letter).
        /// </summary>
        public static string RegExErrMsg_START_EnChar_EnCharOrDigit_0Ti_END {
            get {
                return ResourceManager.GetString("RegExErrMsg_START_EnChar_EnCharOrDigit_0Ti_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Only hungarian letters are permitted (it also have to start with a letter), the space character and these: , ; ..
        /// </summary>
        public static string RegExErrMsg_START_HuChar_HuCharOrDigitOrSeparator_0Ti_END {
            get {
                return ResourceManager.GetString("RegExErrMsg_START_HuChar_HuCharOrDigitOrSeparator_0Ti_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Only hungarian letters are permitted (it also have to start with a letter), and the space character.
        /// </summary>
        public static string RegExErrMsg_START_HuChar_HuCharOrSpace_0Ti_END {
            get {
                return ResourceManager.GetString("RegExErrMsg_START_HuChar_HuCharOrSpace_0Ti_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Only hungarian letters are permitted (it also have to start with a letter), and the space and the comma (,) characters.
        /// </summary>
        public static string RegExErrMsg_START_HuChar_HuCharOrSpaceOrComma_0Ti_END {
            get {
                return ResourceManager.GetString("RegExErrMsg_START_HuChar_HuCharOrSpaceOrComma_0Ti_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplaceDailyItems method needs a not null list. .
        /// </summary>
        public static string ReplaceDailyItems_method_needs_a_not_null_list__ {
            get {
                return ResourceManager.GetString("ReplaceDailyItems_method_needs_a_not_null_list__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplaceDailyItems method replaces only 1 day, the item&apos;s dates must be the same (day).
        /// </summary>
        public static string ReplaceDailyItems_method_replaces_only_1_day__the_item_s_dates_must_be_the_same__day_ {
            get {
                return ResourceManager.GetString("ReplaceDailyItems_method_replaces_only_1_day__the_item_s_dates_must_be_the_same__" +
                        "day_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredErrorMessageFormat {
            get {
                return ResourceManager.GetString("RequiredErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string Save_changes_ {
            get {
                return ResourceManager.GetString("Save_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0} statistics - Error!.
        /// </summary>
        public static string Saving_0__statistics___Error__FORMAT__ {
            get {
                return ResourceManager.GetString("Saving_0__statistics___Error__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0} statistics - OK.
        /// </summary>
        public static string Saving_0__statistics___OK__FORMAT__ {
            get {
                return ResourceManager.GetString("Saving_0__statistics___OK__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving monthly summary file - Error!.
        /// </summary>
        public static string Saving_Monthly_summary_file___Error_ {
            get {
                return ResourceManager.GetString("Saving_Monthly_summary_file___Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving monthly summary file - Successfully.
        /// </summary>
        public static string Saving_Monthly_summary_file___Successfully {
            get {
                return ResourceManager.GetString("Saving_Monthly_summary_file___Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So these modifications did not apply in the database: .
        /// </summary>
        public static string So_these_modifications_did_not_apply_in_the_database {
            get {
                return ResourceManager.GetString("So_these_modifications_did_not_apply_in_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} have to be at most {1} characters long.
        /// </summary>
        public static string StringLengthMaxErrorMessageFormat {
            get {
                return ResourceManager.GetString("StringLengthMaxErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} have to be at least {2}, at most {1} characters long.
        /// </summary>
        public static string StringLengthMinMaxErrorMessageFormat {
            get {
                return ResourceManager.GetString("StringLengthMinMaxErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum:.
        /// </summary>
        public static string Sum_ {
            get {
                return ResourceManager.GetString("Sum_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryEngineBase.ReadData failed. .
        /// </summary>
        public static string SummaryEngineBase_ReadData_failed_ {
            get {
                return ResourceManager.GetString("SummaryEngineBase_ReadData_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryItem InsertOrUpdate failed. .
        /// </summary>
        public static string SummaryItem_InsertOrUpdate_failed__ {
            get {
                return ResourceManager.GetString("SummaryItem_InsertOrUpdate_failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryItem InsertOrUpdate failed (MS SQL).
        /// </summary>
        public static string SummaryItem_InsertOrUpdate_failed__MS_SQL_ {
            get {
                return ResourceManager.GetString("SummaryItem_InsertOrUpdate_failed__MS_SQL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryItem InsertOrUpdate failed (SQLite).
        /// </summary>
        public static string SummaryItem_InsertOrUpdate_failed_SQLite_ {
            get {
                return ResourceManager.GetString("SummaryItem_InsertOrUpdate_failed_SQLite_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryItemManagerAdoNetBase is not implemented for this DbType: {0}.
        /// </summary>
        public static string SummaryItemManagerAdoNetBase_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("SummaryItemManagerAdoNetBase_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryItemManagerEfBase is not implemented for this DbType: {0}.
        /// </summary>
        public static string SummaryItemManagerEfBase_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("SummaryItemManagerEfBase_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T must be of Enum type. .
        /// </summary>
        public static string T_must_be_of_Enum_type__ {
            get {
                return ResourceManager.GetString("T_must_be_of_Enum_type__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enumeration does not have any value for {1}.
        /// </summary>
        public static string The__0__enumeration_does_not_have_any_value_for__1__FORMAT__ {
            get {
                return ResourceManager.GetString("The__0__enumeration_does_not_have_any_value_for__1__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;RootDir&apos; config entry either have to be empty or contain a full path. .
        /// </summary>
        public static string The__RootDir__config_entry_either_have_to_be_empty_or_contain_a_full_path__ {
            get {
                return ResourceManager.GetString("The__RootDir__config_entry_either_have_to_be_empty_or_contain_a_full_path__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will now create the necessary directories. .
        /// </summary>
        public static string The_app_will_now_create_the_necessary_directories {
            get {
                return ResourceManager.GetString("The_app_will_now_create_the_necessary_directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s configuration is the following:.
        /// </summary>
        public static string The_application_s_configuration_ {
            get {
                return ResourceManager.GetString("The_application_s_configuration_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now create the database file, this can take even a few minutes..
        /// </summary>
        public static string The_application_will_now_create_the_database_file__this_can_take_even_a_few_minutes_ {
            get {
                return ResourceManager.GetString("The_application_will_now_create_the_database_file__this_can_take_even_a_few_minut" +
                        "es_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ChangeSummaryDateFromCode class can not access null value in ctor. .
        /// </summary>
        public static string The_ChangeSummaryDateFromCode_class_can_not_access_null_value_in_ctor__ {
            get {
                return ResourceManager.GetString("The_ChangeSummaryDateFromCode_class_can_not_access_null_value_in_ctor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen expense item already exists. .
        /// </summary>
        public static string The_chosen_expense_item_already_exists__ {
            get {
                return ResourceManager.GetString("The_chosen_expense_item_already_exists__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database tables are ready/have been emptied!.
        /// </summary>
        public static string The_database_tables_are_ready__have_been_emptied {
            get {
                return ResourceManager.GetString("The_database_tables_are_ready__have_been_emptied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EnumValues class needs an enum input. .
        /// </summary>
        public static string The_EnumValues_class_needs_an_enum_input__ {
            get {
                return ResourceManager.GetString("The_EnumValues_class_needs_an_enum_input__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exin expense-income summarizer application welcomes you :).
        /// </summary>
        public static string The_Exin_expenses_incomes_summarizer_application_welcomes_you_ {
            get {
                return ResourceManager.GetString("The_Exin_expenses_incomes_summarizer_application_welcomes_you_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file choosen for use: .
        /// </summary>
        public static string The_file_choosen_for_use_ {
            get {
                return ResourceManager.GetString("The_file_choosen_for_use_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following enum is probably not localized yet.
        /// </summary>
        public static string The_following_enum_is_probably_not_localized_yet {
            get {
                return ResourceManager.GetString("The_following_enum_is_probably_not_localized_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImportData project need to be configured to read data from database. You must not use the filesystem for it this time.
        ///&lt;add key=&quot;ReadMode&quot; value=&quot;FromDb&quot; /&gt;.
        /// </summary>
        public static string The_ImportData_project_need_to_be_configured_to_read_data_from_database___ {
            get {
                return ResourceManager.GetString("The_ImportData_project_need_to_be_configured_to_read_data_from_database___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ImportData project need to be configured to use AdoNet to db access, because there are methods directly using AdoNet.
        ///&lt;add key=&quot;DbAccessMode&quot; value=&quot;AdoNet&quot; /&gt;.
        /// </summary>
        public static string The_ImportData_project_need_to_be_configured_to_use_AdoNet_to_db_access___ {
            get {
                return ResourceManager.GetString("The_ImportData_project_need_to_be_configured_to_use_AdoNet_to_db_access___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monthly directory created. .
        /// </summary>
        public static string The_monthly_directory_created_ {
            get {
                return ResourceManager.GetString("The_monthly_directory_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reading of data is not implemented for this: .
        /// </summary>
        public static string The_reading_of_data_is_not_implemented_for_this_ {
            get {
                return ResourceManager.GetString("The_reading_of_data_is_not_implemented_for_this_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving of expense statistics was unsuccessful. .
        /// </summary>
        public static string The_saving_of_expense_statistics_was_unsuccessful_ {
            get {
                return ResourceManager.GetString("The_saving_of_expense_statistics_was_unsuccessful_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving of the daily expenses was unsuccessful. .
        /// </summary>
        public static string The_saving_of_the_daily_expenses_was_unsuccessful_ {
            get {
                return ResourceManager.GetString("The_saving_of_the_daily_expenses_was_unsuccessful_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving of the data was unsuccessful, there were invalid values among them. Fix them, then save again! .
        /// </summary>
        public static string The_saving_of_the_data_was_unsuccessful__there_were_invalid_values_among_them__Fix_them__then_save_again {
            get {
                return ResourceManager.GetString("The_saving_of_the_data_was_unsuccessful__there_were_invalid_values_among_them__Fi" +
                        "x_them__then_save_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving of the income statistics was unsuccessful. .
        /// </summary>
        public static string The_saving_of_the_income_statistics_was_unsuccessful_ {
            get {
                return ResourceManager.GetString("The_saving_of_the_income_statistics_was_unsuccessful_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving of the monthly incomes was unsuccessful. .
        /// </summary>
        public static string The_saving_of_the_monthly_incomes_was_unsuccessful_ {
            get {
                return ResourceManager.GetString("The_saving_of_the_monthly_incomes_was_unsuccessful_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SerializeToLog is not implemented to this log mode: .
        /// </summary>
        public static string The_SerializeToLog_is_not_implemented_to_this_log_mode__ {
            get {
                return ResourceManager.GetString("The_SerializeToLog_is_not_implemented_to_this_log_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQLite database file is ready!.
        /// </summary>
        public static string The_SQLite_database_file_is_ready {
            get {
                return ResourceManager.GetString("The_SQLite_database_file_is_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theoretically later date is earlier than the theoretically earlier date. .
        /// </summary>
        public static string The_theoretically_later_date_is_earlier_than_the_theoretically_earlier_date_ {
            get {
                return ResourceManager.GetString("The_theoretically_later_date_is_earlier_than_the_theoretically_earlier_date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to convert must be of type Enum. .
        /// </summary>
        public static string The_value_to_convert_must_be_of_type_Enum__ {
            get {
                return ResourceManager.GetString("The_value_to_convert_must_be_of_type_Enum__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no incomes in this month. .
        /// </summary>
        public static string There_are_no_incomes_in_this_month {
            get {
                return ResourceManager.GetString("There_are_no_incomes_in_this_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was error while reading the daily files:.
        /// </summary>
        public static string There_was_error_while_reading_the_daily_files_ {
            get {
                return ResourceManager.GetString("There_was_error_while_reading_the_daily_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} entity does not contain any DisplayName value. It&apos;s Name value will be used instead. .
        /// </summary>
        public static string This__0__entity_does_not_contain_any_DisplayName_value___ {
            get {
                return ResourceManager.GetString("This__0__entity_does_not_contain_any_DisplayName_value___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: .
        /// </summary>
        public static string Title_ {
            get {
                return ResourceManager.GetString("Title_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s expenses loading....
        /// </summary>
        public static string Today_s_expenses_loading__ {
            get {
                return ResourceManager.GetString("Today_s_expenses_loading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s .
        /// </summary>
        public static string Todays_ {
            get {
                return ResourceManager.GetString("Todays_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TProperty must be a member of a class.
        /// </summary>
        public static string TProperty_must_be_a_member_of_a_class {
            get {
                return ResourceManager.GetString("TProperty_must_be_a_member_of_a_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction items.
        /// </summary>
        public static string transaction_items {
            get {
                return ResourceManager.GetString("transaction_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionItemManagerAdoNetFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string TransactionItemManagerAdoNetFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("TransactionItemManagerAdoNetFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionItemManagerEfFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string TransactionItemManagerEfFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("TransactionItemManagerEfFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try with another database access mode. .
        /// </summary>
        public static string Try_with_another_database_access_mode {
            get {
                return ResourceManager.GetString("Try_with_another_database_access_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit: .
        /// </summary>
        public static string Unit_ {
            get {
                return ResourceManager.GetString("Unit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit.
        /// </summary>
        public static string unit_lowercase {
            get {
                return ResourceManager.GetString("unit_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitManagerAdoNetFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string UnitManagerAdoNetFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("UnitManagerAdoNetFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitManagerCommonBase.RefreshCache is not implemented for ReadMode: .
        /// </summary>
        public static string UnitManagerCommonBase_RefreshCache_is_not_implemented_for_ReadMode__ {
            get {
                return ResourceManager.GetString("UnitManagerCommonBase_RefreshCache_is_not_implemented_for_ReadMode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitManagerEfFactory is not implemented for this DbType: {0}.
        /// </summary>
        public static string UnitManagerEfFactory_is_not_implemented_for_this_DbType__FORMAT__ {
            get {
                return ResourceManager.GetString("UnitManagerEfFactory_is_not_implemented_for_this_DbType__FORMAT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exin - Expenses/Incomes.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis max (thousands): .
        /// </summary>
        public static string Y_axis_max__ {
            get {
                return ResourceManager.GetString("Y_axis_max__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start your work now ;).
        /// </summary>
        public static string You_can_start_your_work_ {
            get {
                return ResourceManager.GetString("You_can_start_your_work_", resourceCulture);
            }
        }
    }
}
