var COLOR_TRANSPARENT = "transparent";
var COLOR_GOOD_GREEN = "#05F00A";
var COLOR_BAD_RED = "#F90C0C";
var DEFAULT_ANIMATION_DURATION = 500;
var DEFAULT_FLASH_DURATION = 500;
var DEFAULT_TOGGLE_DURATION = 500;
var DEFAULT_FADING_DURATION = 500;
var DEFAULT_FADING_DURATION_HALF = 250;