//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DAL.DataBase.EntityFramework.EntitiesMsSql
{
    public partial class Category_MsSql
    {
        public Category_MsSql()
        {
            this.SummaryItems = new HashSet<SummaryItem_MsSql>();
            this.TransactionItems = new HashSet<TransactionItem_MsSql>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<SummaryItem_MsSql> SummaryItems { get; set; }
        public virtual ICollection<TransactionItem_MsSql> TransactionItems { get; set; }
    }
}
