//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DAL.DataBase.EntityFramework.EntitiesMsSql
{
    public partial class ExinEfMsSqlContext : DbContext
    {
        public ExinEfMsSqlContext()
            : base("name=ExinEfMsSqlContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category_MsSql> Category { get; set; }
        public DbSet<SummaryItem_MsSql> SummaryItem { get; set; }
        public DbSet<TransactionItem_MsSql> TransactionItem { get; set; }
        public DbSet<Unit_MsSql> Unit { get; set; }
    }
}
