//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DAL.DataBase.EntityFramework.EntitiesMsSql
{
    public partial class SummaryItem_MsSql
    {
        public int ID { get; set; }
        public int Amount { get; set; }
        public int CategoryID { get; set; }
        public DateTime Date { get; set; }
    
        public virtual Category_MsSql Category { get; set; }
    }
}
