//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DAL.DataBase.EntityFramework.EntitiesMsSql
{
    public partial class TransactionItem_MsSql
    {
        public int ID { get; set; }
        public int Amount { get; set; }
        public int Quantity { get; set; }
        public int UnitID { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public DateTime Date { get; set; }
        public int CategoryID { get; set; }
        public bool IsExpenseItem { get; set; }
        public bool IsIncomeItem { get; set; }
    
        public virtual Category_MsSql Category { get; set; }
        public virtual Unit_MsSql Unit { get; set; }
    }
}
