//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DAL.DataBase.EntityFramework.EntitiesSqlite
{
    public partial class Category_Sqlite
    {
        public Category_Sqlite()
        {
            this.SummaryItems = new HashSet<SummaryItem_Sqlite>();
            this.TransactionItems = new HashSet<TransactionItem_Sqlite>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<SummaryItem_Sqlite> SummaryItems { get; set; }
        public virtual ICollection<TransactionItem_Sqlite> TransactionItems { get; set; }
    }
}
