//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase.EntityFramework.EntitiesSqlite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExinEfSqliteContext : DbContext
    {
        public ExinEfSqliteContext()
            : base("name=ExinEfSqliteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category_Sqlite> Category { get; set; }
        public DbSet<SummaryItem_Sqlite> SummaryItem { get; set; }
        public DbSet<TransactionItem_Sqlite> TransactionItem { get; set; }
        public DbSet<Unit_Sqlite> Unit { get; set; }
    }
}
