//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase.EntityFramework.EntitiesSqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryItem_Sqlite
    {
        public long ID { get; set; }
        public long Amount { get; set; }
        public long CategoryID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Category_Sqlite Category { get; set; }
    }
}
