//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase.EntityFramework.EntitiesSqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionItem_Sqlite
    {
        public long ID { get; set; }
        public long Amount { get; set; }
        public long Quantity { get; set; }
        public long UnitID { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public long CategoryID { get; set; }
        public bool IsExpenseItem { get; set; }
        public bool IsIncomeItem { get; set; }
    
        public virtual Category_Sqlite Category { get; set; }
        public virtual Unit_Sqlite Unit { get; set; }
    }
}
